### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by pispuso** [elcuervo/tangalanga#1]
Hello fellow Argentinian.

I don;t have much experience with Go. Could you guide me with the install steps? I would love to try Tangalanga.

Thanks!

**Comment by TheAnachronism** [comment]
I'd like that too
Bit confused about how I get that zpk token.

**Comment by elcuervo** [comment]
> Hello fellow Argentinian.

Close, but not quite.

> 
> I don;t have much experience with Go. Could you guide me with the install steps? I would love to try Tangalanga.
> 
> Thanks!

You can find a prebuilt (and prebaked with a token) version here https://github.com/elcuervo/tangalanga/releases/tag/v0.1-baked

I'll update the README with more specific information

**Comment by elcuervo** [comment]
There's now a https://github.com/elcuervo/tangalanga#install
And a https://github.com/elcuervo/tangalanga#tokens

**Comment by thebatipibe** [comment]
Hola amigo soy de Perú  uso kali linux virtualizado versión lite , nunca e usado golang y busqué un Boobing  de zoom y en el canal de YouTube Hack Waze hallé esta gran herramienta quiero saber si puedo instalarla  en mi arquitectura arm64  (aarch64) y que requerimientos necesito disculpe , por ser amateur  y desconocer el lenguaje go

**Comment by carlosDLX** [comment]
Hi
